get_otp_screen
NewTab-Technnologies/Ride-Bhaiya pull request #32
Opened 2024-05-13 06:55 UTC by tanishq-2208

2024-05-21 21:51 UTC, maheshalyana commented on lib/main.dart
remove any changes in the main.dart

2024-05-21 21:57 UTC, maheshalyana requested changes
remove changes from main.dart and we good to go

2024-05-22 05:46 UTC, tanishq-2208 commented on lib/main.dart
changes done.

2024-05-22 08:33 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/184887cf-2438-4a03-895c-7d411b1a8cab)

Font should be changed.. moving to development

2024-05-22 09:29 UTC, maheshalyana requested changes
change the font style and move to Review

2024-05-22 10:34 UTC, maheshalyana requested changes

2024-05-22 10:34 UTC, maheshalyana commented on lib/main.dart
remove changes from main.dart

2024-05-22 10:52 UTC, tanishq-2208 commented on lib/main.dart
Done

2024-05-22 14:16 UTC, maheshalyana approved these changes

2024-05-22 15:32 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/bc491a89-bceb-40d3-bcbf-d132c7d8608c)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/7a5ba986-f759-4df1-a967-c466a28a7211)

Screen matches with the design and test cases passed.. moving it to acceptance.

2024-05-22 15:45 UTC, merged