view_requests_screen
NewTab-Technnologies/Ride-Bhaiya pull request #37
Opened 2024-05-13 11:44 UTC by tanishq-2208

2024-05-23 12:27 UTC, maheshalyana requested changes

2024-05-23 12:27 UTC, maheshalyana commented on lib/fonts/Poppins-Medium.ttf
place this file in correct directory

2024-05-28 08:02 UTC, maheshalyana approved these changes

2024-05-28 10:51 UTC, Abhi-0987 approved these changes
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/801dcbe8-c9f3-4bc7-a521-bc00d0376e42)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/90a5856f-1b28-4244-ac9d-6c9a7a4aaa03)
Screen matches with the design and the test cases passed. Moving it to accpetance.

2024-05-28 10:58 UTC, merged