[FEATURE] Implemented form component for ride
NewTab-Technnologies/Ride-Bhaiya pull request #38
Opened 2024-05-13 12:03 UTC by akshaya-527

2024-05-23 12:33 UTC, maheshalyana requested changes

2024-05-24 07:41 UTC, maheshalyana approved these changes

2024-05-24 08:32 UTC, Abhi-0987 submitted a review, later dismissed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/4354efc4-0b4a-47e0-886d-d3f575c18349)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/e9b817c2-95e6-4b5b-96a2-f9d93f78efcf)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/e412e6b8-0889-4323-9443-f14d1ad19e2e)

Screen matches the design and test cases passed

2024-05-25 08:14 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/1f62155c-8a88-4d03-be2f-a5805219c27a)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/585ac5c4-4e1a-4d2f-abb6-eaf59b64fd79)

There is an issue with icons, I tried to check in web too it's the same. Moving back to development.

2024-05-27 09:49 UTC, Abhi-0987 approved these changes
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/871df233-c5e9-4307-95c6-b4dabebf7764)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/65c0fbcc-2211-4f75-a2cb-e5029e51fafa)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/203ac725-2aa2-4f1e-96c7-acd98dd65ef6)

Screen matches the design and tests passed. Moving to acceptance.

2024-05-27 10:06 UTC, merged