12-schedule-request-ride -- Scedule/Request a ride screens
NewTab-Technnologies/Ride-Bhaiya pull request #39
Opened 2024-05-13 15:26 UTC by Saketh0809

2024-05-21 13:34 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/8ca01e8d-3894-40a5-b609-c4a4785c5aee)

Changes needed button paddings and the text size

2024-05-21 21:52 UTC, maheshalyana approved these changes

2024-05-22 06:53 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/4eff56e6-d3f6-4c0e-83e2-3cc2252088b3)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/6909798f-d05f-425d-8cdc-3ec77f1626d4)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/0bead390-c9c4-4476-ab9a-0998703062d5)

It matches with the design and the test cases are passed.. moving it to acceptance

2024-05-22 10:32 UTC, maheshalyana requested changes

2024-05-22 11:07 UTC, maheshalyana approved these changes

2024-05-22 11:38 UTC, merged