get ride files are modified
NewTab-Technnologies/Ride-Bhaiya pull request #42
Opened 2024-05-14 08:10 UTC by Nethidheeraj

2024-05-21 12:03 UTC, maheshalyana requested changes
place assets: in correct position

2024-05-22 10:29 UTC, maheshalyana approved these changes

2024-05-22 13:26 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/a9e553d1-f249-46de-80a9-a29c8f4e465c)

Button padding and the text alignment should be checked.. moving it to development

2024-05-22 14:00 UTC, maheshalyana requested changes
Change fonts and use proper icons

2024-05-22 14:22 UTC, maheshalyana approved these changes

2024-05-22 14:22 UTC, merged