Created-Schedule-Screen
NewTab-Technnologies/Ride-Bhaiya pull request #43
Opened 2024-05-15 07:07 UTC by Pradeep-O

2024-05-25 20:33 UTC, maheshalyana requested changes

2024-05-25 20:33 UTC, maheshalyana commented on lib/screens/view_schedule_screen.dart
> +class ScheduleScreen extends StatefulWidget {
`ViewScheduleScreen` or `SchedulesScreen` because we already have that class name I think for creating Schedule, if not also we may get confused in future

2024-05-25 20:33 UTC, maheshalyana commented on lib/widgets/view_request_schedule_tile.dart
There is already a tile, use it instead which have been used in homescreen

2024-05-25 20:33 UTC, maheshalyana commented on widgets/one_request_ride_schedule_tile.dart
What is this file again

2024-05-26 05:26 UTC, Pradeep-O commented on lib/screens/view_schedule_screen.dart
> +class ScheduleScreen extends StatefulWidget {
There is a class named `ScheduleRideScreen.`
I will go with `ViewScheduleScreen`

2024-05-26 05:30 UTC, Pradeep-O commented on widgets/one_request_ride_schedule_tile.dart
Created a tile with only one button then renamed it to `view_request_schedule_tile`.
Forgot to remove it.
I removed it now.

2024-05-26 05:37 UTC, Pradeep-O commented on lib/widgets/view_request_schedule_tile.dart
The `RideDetailsTile` has two buttons in it but we require only one button for `ViewScheduleScreen`, so I created a new tile.

If I reuse `RideDetailsButton`, I should do some minor changes in `request_ride_schedule_tile` and `home_screen_tab_structure` files to get only one button for `ViewScheduleScreen` and two buttons for `HomeScreen`.

2024-05-27 11:47 UTC, maheshalyana approved these changes

2024-05-27 12:08 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/9c205aca-67a3-421f-811b-b781d38953d3)

The padding between the view schedules text and the tiles is pushing tiles to down of the screen.. reducing would be better, and if possible the space between the details and the contact button should also reduce.

2024-05-27 12:52 UTC, Pradeep-O commented
> ![image](https://private-user-images.githubusercontent.com/124353488/334094922-9c205aca-67a3-421f-811b-b781d38953d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTIxNTcsIm5iZiI6MTcxNjgxMTg1NywicGF0aCI6Ii8xMjQzNTM0ODgvMzM0MDk0OTIyLTljMjA1YWNhLTY3YTMtNDIxZi04MTFiLWI3ODFkMzg5NTNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMjEwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzkxMDlmYWE2YzdmMGVkMWU1ZTg4OThhNzQ2ZmFlZTc2MDdjN2Q0NDYxYTZkYTY1NTQ3MTkwYTY5Yzg4YzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WWq_MAxDGxJCbjXm99T3IvLuw7m9OZX2OZYdLfJlN24)
> 
> The padding between the view schedules text and the tiles is pushing tiles to down of the screen.. reducing would be better, and if possible the space between the details and the contact button should also reduce. Moving back to development.

2024-05-27 12:59 UTC, maheshalyana commented on lib/screens/view_schedule_screen.dart
> +                    child: ScheduleTwoTile(values: values)),
Ther won't always be 2 tiles so try doing this
```
Column(
children: [values, values].map((schedule) => ScheduleOneTile(values: schedule)).toList(),
)
```

2024-05-27 13:03 UTC, Pradeep-O commented on lib/screens/view_schedule_screen.dart
> +                    child: ScheduleTwoTile(values: values)),
Ok sir

2024-05-27 14:57 UTC, maheshalyana approved these changes

2024-05-27 17:47 UTC, Abhi-0987 approved these changes
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/866bba60-5e11-4492-a556-ef0b781b7dd6)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/85715c04-34b6-464c-a69c-9994d59ca969)
Screen matches with the design and test cases passed. Moving to acceptance.

2024-05-28 05:23 UTC, merged