6 otp verification screen
NewTab-Technnologies/Ride-Bhaiya pull request #51
Opened 2024-05-21 12:37 UTC by ushamsharath

2024-05-21 21:58 UTC, maheshalyana requested changes

2024-05-21 21:58 UTC, maheshalyana commented on lib/main.dart
there should be now canges in main.dart

2024-05-22 05:40 UTC, ushamsharath commented on lib/main.dart
updated the changes

2024-05-22 07:56 UTC, maheshalyana approved these changes

2024-05-22 10:11 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/e7a4b4da-f67c-4f7c-b51b-6b3ca6f1d0cc)

Font should be changed.. moving to development

2024-05-22 10:30 UTC, maheshalyana approved these changes

2024-05-22 11:03 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/7d0ecc3e-1d2b-4615-a978-83b6b3bbdc33)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/f04c2629-9891-4495-92bc-a1dbd248aed5)

Design matched and test cases are passed.. moving to acceptance.

2024-05-22 11:09 UTC, merged