Navigations
NewTab-Technnologies/Ride-Bhaiya pull request #53
Opened 2024-05-23 06:21 UTC by Abhi-0987

2024-05-28 15:24 UTC, maheshalyana commented
What about viewmore button

2024-05-29 07:44 UTC, maheshalyana requested changes

2024-05-29 07:44 UTC, maheshalyana commented on lib/screens/home_screen_tab_structure.dart
> +      path: 'one',
instead send the class directly `path: ViewRequestsScreen()`

2024-05-29 08:16 UTC, Abhi-0987 commented on lib/screens/home_screen_tab_structure.dart
> +      path: 'one',
I am unable to pass the route like that. I tried doing that first. I tried to send class directly by keeping the datatype as dynamic. But there was an error in the `MaterialPageRoute` it was giving error if I use that path there. Then at last I did this.

2024-05-29 10:06 UTC, maheshalyana commented on lib/screens/home_screen_tab_structure.dart
> +      path: 'one',
Okay

2024-05-29 10:06 UTC, maheshalyana approved these changes

2024-05-29 10:38 UTC, tanishq-2208 approved these changes
https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/152472135/253b466b-9e19-43b5-bb9c-3334bbfd2696

Working As Expected.

2024-05-29 10:49 UTC, merged