[Featured] implemented 9-ride-request-schedule-tile
NewTab-Technnologies/Ride-Bhaiya pull request #54
Opened 2024-05-23 12:25 UTC by Pradeep-O

2024-05-23 13:16 UTC, maheshalyana requested changes

2024-05-23 13:16 UTC, maheshalyana commented on lib/widgets/request_ride_schedule_tile.dart
> +import 'package:flutter/material.dart';
Choose a proper tile name

2024-05-23 13:16 UTC, maheshalyana commented on lib/screens/home_screen_tab_structure.dart
> +                  TileTwoButtons(values: values),
both should be list view, that means, there should be scrolling of the tiles vertically

2024-05-23 13:32 UTC, Pradeep-O commented on lib/widgets/request_ride_schedule_tile.dart
> +import 'package:flutter/material.dart';
Changing to RideScheduleTile

2024-05-23 13:51 UTC, maheshalyana commented on lib/widgets/request_ride_schedule_tile.dart
> +import 'package:flutter/material.dart';
how about `RideDetailsTile`

2024-05-23 13:53 UTC, maheshalyana requested changes

2024-05-23 13:53 UTC, maheshalyana commented on lib/screens/home_screen_tab_structure.dart
> -
Don't remove these Classes, instead add the widget class in these classes and use these classes in the tabs

2024-05-23 15:17 UTC, Pradeep-O commented on lib/widgets/request_ride_schedule_tile.dart
> +import 'package:flutter/material.dart';
I will go with it sir.

2024-05-23 16:17 UTC, maheshalyana approved these changes

2024-05-23 16:50 UTC, Abhi-0987 reviewed
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/dd64d27c-71a4-42df-b73c-b7beea0fed25)

Padding is needed at the top..

2024-05-23 17:58 UTC, maheshalyana requested changes

2024-05-23 17:58 UTC, maheshalyana commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RideDetailsTile), findsOneWidget);
What is there is not Schedule, then it will fail, so remove this one

2024-05-23 18:33 UTC, Pradeep-O commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RideDetailsTile), findsOneWidget);
ScheduleTile has findsNothing in this.

2024-05-24 08:01 UTC, Pradeep-O commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RideDetailsTile), findsOneWidget);
Removed them

2024-05-24 08:08 UTC, maheshalyana requested changes

2024-05-24 08:08 UTC, maheshalyana commented on test/home_screen_tab_structure_test.dart
> -    expect(find.text('Latest Schedules'), findsOneWidget);
Why did you removed these test cases

2024-05-24 08:08 UTC, maheshalyana commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RequestTile), findsOneWidget);
Remove this test case we don't need them

2024-05-24 08:08 UTC, maheshalyana commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RequestTile), findsNothing);
remove these test cases

2024-05-24 08:16 UTC, Pradeep-O commented on test/home_screen_tab_structure_test.dart
> -    expect(find.text('Latest Schedules'), findsOneWidget);
There will be no text output for the classes as seen in the Figma.
Before modification, they were there to represent the tile, but after modification we just need the tile and its contents, no need for the Texts like 'Latest Schedules' and 'Latest Requests.

2024-05-24 08:17 UTC, Pradeep-O commented on test/home_screen_tab_structure_test.dart
> +    expect(find.byType(RequestTile), findsNothing);
Ok sir

2024-05-24 08:34 UTC, maheshalyana commented on test/home_screen_tab_structure_test.dart
> -    expect(find.text('Latest Schedules'), findsOneWidget);
I think these are being rendered in tab bar right?

2024-05-24 08:41 UTC, Pradeep-O commented on test/home_screen_tab_structure_test.dart
> -    expect(find.text('Latest Schedules'), findsOneWidget);
Yeah got it

2024-05-24 09:56 UTC, maheshalyana approved these changes

2024-05-24 10:54 UTC, Abhi-0987 approved these changes
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/fefa06d3-4824-4239-9bce-ee45b516b994)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/26453a39-4dd1-4f88-97ee-473801811366)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/fe086806-909b-4827-aef2-033730df938d)

Screen matches with the design and test case passed..moving it to acceptance

2024-05-24 11:10 UTC, merged