17 firebase setup for the application
NewTab-Technnologies/Ride-Bhaiya pull request #56
Opened 2024-05-24 19:13 UTC by tanishq-2208

2024-05-24 20:16 UTC, maheshalyana requested changes

2024-05-24 20:16 UTC, maheshalyana commented on pubspec.yaml
> +  equatable: ^2.0.3
Are we using these packages

2024-05-25 04:05 UTC, tanishq-2208 commented on pubspec.yaml
> +  equatable: ^2.0.3
Its better to use them....these help in enhancing the functionality of our flutter application.

2024-05-26 06:43 UTC, maheshalyana commented on pubspec.yaml
> +  equatable: ^2.0.3
Yeah I know, but I don't think we are going to use them in app now, when we'll be using then we can add them if needed

2024-05-27 03:04 UTC, tanishq-2208 commented on pubspec.yaml
> +  equatable: ^2.0.3
okay

2024-06-03 08:20 UTC, maheshalyana approved these changes

2024-06-03 09:36 UTC, merged