[FEATURE] Implemented Sign up screen
NewTab-Technnologies/Ride-Bhaiya pull request #60
Opened 2024-05-29 12:55 UTC by ushamsharath

2024-05-29 13:28 UTC, maheshalyana requested changes

2024-05-29 13:28 UTC, maheshalyana commented on lib/screens/sign_up_screen.dart
> +class SignUp extends StatelessWidget {
`SingUpScreen`

2024-05-29 13:28 UTC, maheshalyana commented on lib/screens/sign_up_screen.dart
Instead of doing this create a flag for OTPVerificationScreen like a string flag = 'signup' or 'login', depending on this show the field of name

2024-05-29 15:57 UTC, maheshalyana approved these changes

2024-05-30 03:53 UTC, Abhi-0987 approved these changes
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/1e5ac7cb-3063-4a76-bfca-486f2c68e670)
![image](https://github.com/NewTab-Technnologies/Ride-Bhaiya/assets/124353488/051a8edf-af3c-48ec-a456-ed37612e44ab)
Screen matches with the design and test cases passed. Moving it to acceptance.

2024-05-30 09:04 UTC, merged